name: Deploy to EC2

on:
  push:
    branches:
      - main
  schedule:
    - cron: '*/10 * * * *'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: 13.221.64.172
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd ~/cloud-cost-aware-pipeline

            echo "Reset & pull latest code"
            git reset --hard
            git pull

            echo "Running monitoring script"
            python3 cost_check.py

            echo "Stopping old containers"
            docker ps -q | xargs -r docker stop
            docker ps -aq | xargs -r docker rm

            echo "Starting new container"
            docker run -d -p 80:80 -v $(pwd):/usr/share/nginx/html nginx

            echo "Deployment complete"
